package edu.emory.cci.aiw.cvrg.eureka.common.comm;

/*
 * #%L
 * Eureka Common
 * %%
 * Copyright (C) 2012 - 2013 Emory University
 * %%
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * #L%
 */
import edu.emory.cci.aiw.cvrg.eureka.common.entity.JobEvent;
import edu.emory.cci.aiw.cvrg.eureka.common.entity.JobState;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.Date;
import java.util.List;
import org.apache.commons.lang.builder.ToStringBuilder;

/**
 *
 * @author Andrew Post
 */
public class Job {

	public static class TimestampComparator implements Comparator<Job> {

		@Override
		public int compare(Job t, Job t1) {
			Date tt = t.getTimestamp();
			Date t1t = t1.getTimestamp();
			if (tt == null && t1t == null) {
				return 0;
			} else if (t1t == null) {
				return 1;
			} else if (tt == null) {
				return -1;
			} else {
				return tt.compareTo(t1t);
			}
		}
	}
	private Long id;
	/**
	 * The initial timestamp when the job was started.
	 */
	private Date timestamp;
	/**
	 * The unique identifier of the configuration to use for this job.
	 */
	private String sourceConfigId;
	/**
	 * The unique identifier of the configuration to use for this job.
	 */
	private String destinationId;
	private String username;
	private JobState state;
	private List<JobEvent> jobEvents;

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Date getTimestamp() {
		return timestamp;
	}

	public void setTimestamp(Date timestamp) {
		this.timestamp = timestamp;
	}

	public String getSourceConfigId() {
		return sourceConfigId;
	}

	public void setSourceConfigId(String sourceConfigId) {
		this.sourceConfigId = sourceConfigId;
	}

	public String getDestinationId() {
		return destinationId;
	}

	public void setDestinationId(String destinationId) {
		this.destinationId = destinationId;
	}

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public JobState getState() {
		return state;
	}

	public void setState(JobState state) {
		this.state = state;
	}

	public List<JobEvent> getJobEvents() {
		return jobEvents;
	}

	public void setJobEvents(List<JobEvent> jobEvents) {
		this.jobEvents = jobEvents;
	}

	/**
	 * Return a list of messages generated by the job.
	 *
	 * @return The list of messages.
	 */
	public List<String> messages() {
		final List<String> messages = new ArrayList<String>();
		for (JobEvent event : this.jobEvents) {
			final String message = event.getMessage();
			if (message != null) {
				messages.add(message);
			}
		}
		return messages;
	}

	public JobStatus toJobStatus() {
		JobStatus jobStatus = new JobStatus();
		jobStatus.setState(getState());
		jobStatus.setMessages(messages());
		jobStatus.setUploadTime(getTimestamp());
		return jobStatus;
	}

	@Override
	public String toString() {
		return ToStringBuilder.reflectionToString(this);
	}
}
