package edu.emory.cci.aiw.cvrg.eureka.common.comm;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.xml.bind.annotation.XmlRootElement;

import org.codehaus.jackson.annotate.JsonIgnore;

import edu.emory.cci.aiw.cvrg.eureka.common.entity.FileError;
import edu.emory.cci.aiw.cvrg.eureka.common.entity.FileUpload;
import edu.emory.cci.aiw.cvrg.eureka.common.entity.FileWarning;
import edu.emory.cci.aiw.cvrg.eureka.common.entity.Job;
import edu.emory.cci.aiw.cvrg.eureka.common.entity.JobEvent;

/**
 * A communication bean to transfer information about a user's job.
 * 
 * @author hrathod
 * 
 */
@XmlRootElement
public class JobInfo {
	/**
	 * The total number of steps in the process.
	 */
	private int totalSteps = 7;
	/**
	 * The file upload for the job being processed.
	 */
	private FileUpload fileUpload;
	/**
	 * The actual running job, if the file upload/validation/processing is
	 * complete.
	 */
	private Job job;

	/**
	 * Get the processing step for the file upload or job.
	 * 
	 * @return The process step that the job is currently on.
	 */
	@JsonIgnore
	public int getCurrentStep() {
		int step;
		boolean activeJob = this.isJobActive();
		boolean activeUpload = this.isUploadActive();

		if (activeUpload) {
			// first, we look for an active upload, and return its status.
			step = this.getUploadStep();
		} else if (activeJob) {
			// else, we look for an active job, and return its status.
			step = this.getJobStep();
		} else {
			// if nothing is active, then find the later of the upload or the
			// job, and return that item's status.
			if (this.job != null && this.fileUpload != null) {
				if (this.job.getTimestamp().after(
						this.fileUpload.getTimestamp())) {
					step = this.getJobStep();
				} else {
					step = this.getUploadStep();
				}
			} else if (this.job != null) {
				step = this.getJobStep();
			} else if (this.fileUpload != null) {
				step = this.getUploadStep();
			} else {
				step = 0;
			}
		}

		return step;
	}

	/**
	 * Return the current status of the job.
	 * 
	 * @return The current step.
	 */
	@JsonIgnore
	private int getJobStep() {
		int step = 0;
		String currentState = this.job.getCurrentState();
		if (currentState.equals("DONE") || currentState.equals("FAILED")
				|| currentState.equals("EXCEPTION")
				|| currentState.equals("INTERRUPTED")) {
			step = 7;
		} else if (currentState.equals("PROCESSING")) {
			step = 6;
		} else if (currentState.equals("CREATED")) {
			step = 5;
		}
		return step;
	}

	/**
	 * Return the current status of the upload.
	 * 
	 * @return The current step.
	 */
	@JsonIgnore
	private int getUploadStep() {
		int step = 0;
		if (this.fileUpload.isCompleted()) {
			step = 4;
		} else if (this.fileUpload.isProcessed()) {
			step = 3;
		} else if (this.fileUpload.isValidated()) {
			step = 2;
		} else {
			step = 1;
		}
		return step;
	}

	/**
	 * Find out whether the job contained in this job information object is
	 * currently active or not.
	 * 
	 * @return True, if the job is active and false otherwise.
	 */
	@JsonIgnore
	private boolean isJobActive() {
		boolean result;
		if (this.job == null) {
			result = false;
		} else {
			String state = this.job.getCurrentState();
			result = (state.equals("CREATED") || state.equals("PROCESSING"));
		}
		return result;
	}

	/**
	 * Find out whether the file upload contained in this job information object
	 * is currently active or not.
	 * 
	 * @return True if the file upload is active, false otherwise.
	 */
	private boolean isUploadActive() {
		boolean result;
		if (this.fileUpload == null) {
			result = false;
		} else {
			result = (this.fileUpload.isCompleted() == false);
		}
		return result;
	}

	/**
	 * Get the timestamp of the latest update for a file job.
	 * 
	 * @return The latest timestamp for the job.
	 */
	@JsonIgnore
	public Date getTimestamp() {
		Date result;
		if (this.job != null) {
			result = this.job.getTimestamp();
		} else if (this.fileUpload != null) {
			result = this.fileUpload.getTimestamp();
		} else {
			result = null;
		}
		return result;
	}

	/**
	 * @return the totalSteps
	 */
	public int getTotalSteps() {
		return this.totalSteps;
	}

	/**
	 * @param inTotalSteps the totalSteps to set
	 */
	public void setTotalSteps(int inTotalSteps) {
		this.totalSteps = inTotalSteps;
	}

	/**
	 * Get a list of messages for the job, including those generated by the file
	 * validation, as well as the running of the job itself.
	 * 
	 * @return The list of messages for the job.
	 */
	@JsonIgnore
	public List<String> getMessages() {
		List<String> messages = new ArrayList<String>();
		if (this.fileUpload != null) {
			messages.addAll(this.getFileUploadMessages());
		}
		if (this.job != null) {
			messages.addAll(this.getJobMessages());
		}
		return messages;
	}

	/**
	 * Return a list of messages generated by the file upload validation.
	 * 
	 * @return The list of messages.
	 */
	private List<String> getFileUploadMessages() {
		List<String> messsages = new ArrayList<String>();
		if (this.fileUpload != null) {
			for (FileWarning fileWarning : this.fileUpload.getWarnings()) {
				messsages.add(fileWarning.toString());
			}
			for (FileError error : this.fileUpload.getErrors()) {
				messsages.add(error.toString());
			}
		}
		return messsages;
	}

	/**
	 * Return a list of messages generated by the job.
	 * 
	 * @return The list of messages.
	 */
	private List<String> getJobMessages() {
		final List<String> messages = new ArrayList<String>();
		if (this.job != null) {
			for (JobEvent event : this.job.getJobEvents()) {
				final String message = event.getMessage();
				if (message != null) {
					messages.add(message);
				}
			}
		}
		return messages;
	}

	/**
	 * @return the fileUpload
	 */
	public FileUpload getFileUpload() {
		return this.fileUpload;
	}

	/**
	 * @param inFileUpload the fileUpload to set
	 */
	public void setFileUpload(FileUpload inFileUpload) {
		this.fileUpload = inFileUpload;
	}

	/**
	 * @return the job
	 */
	public Job getJob() {
		return this.job;
	}

	/**
	 * @param inJob the job to set
	 */
	public void setJob(Job inJob) {
		this.job = inJob;
	}
}
